version: '3'

networks:
  mysql:
    name: ${DB_CONTAINER:-mysql}

volumes:
  mysql_data:
    name: ${DB_CONTAINER:-mysql}

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: ${DB_CONTAINER:-postgres}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - 3307:3307
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql

  adminer:
    image: adminer:latest
    container_name: ${DB_CONTAINER:-adminer}
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: galkaev
    ports:
      - 8080:8080
    networks:
      - mysql



